## YAML Template.
api_platform:
    defaults:
        pagination_items_per_page: 30 # Default value
    swagger:
         api_keys:
             JWT:
                name: Authorization
                type: header